version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
    - mvn clean package
    - mvn clean install

artifacts:
  files:
  - target/complianceOracle-rules-0.0.1-SNAPSHOT.jar
  discard-paths: yes

